-- Create Branches table and seed default data

-- Branches table
CREATE TABLE BRANCHES (
    BRANCH_CODE VARCHAR(50) PRIMARY KEY,
    BRANCH_NAME VARCHAR(255) NOT NULL,
    PARTNER_CODE VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed default branches
MERGE INTO BRANCHES (BRANCH_CODE, BRANCH_NAME, PARTNER_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
KEY (BRANCH_CODE)
VALUES
('MIYAPUR', 'Miyapur Branch', 'SAMASTA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KUKATPALLY', 'Kukatpally Branch', 'SAMASTA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MADHAPUR', 'Madhapur Branch', 'SONATA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GACHIBOWLI', 'Gachibowli Branch', 'SONATA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
