-- Add more comprehensive default master data for testing and development

-- Add more Partners
MERGE INTO PARTNERS (PARTNER_CODE, PARTNER_NAME, IS_ACTIVE, CREATED_AT)
KEY (PARTNER_CODE)
VALUES
('UJJIVAN', 'Ujjivan Small Finance Bank', TRUE, CURRENT_TIMESTAMP),
('BANDHAN', 'Bandhan Bank', TRUE, CURRENT_TIMESTAMP),
('EQUITAS', 'Equitas Small Finance Bank', TRUE, CURRENT_TIMESTAMP),
('FINCARE', 'Fincare Small Finance Bank', TRUE, CURRENT_TIMESTAMP);

-- Add more Products
MERGE INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, IS_ACTIVE, CREATED_AT)
KEY (PRODUCT_CODE)
VALUES
('HOME_LOAN', 'Home Loan', TRUE, CURRENT_TIMESTAMP),
('PERSONAL_LOAN', 'Personal Loan', TRUE, CURRENT_TIMESTAMP),
('VEHICLE_LOAN', 'Vehicle Loan', TRUE, CURRENT_TIMESTAMP),
('GOLD_LOAN', 'Gold Loan', TRUE, CURRENT_TIMESTAMP),
('MSME_LOAN', 'MSME Loan', TRUE, CURRENT_TIMESTAMP),
('AGRICULTURE_LOAN', 'Agriculture Loan', TRUE, CURRENT_TIMESTAMP);

-- Add more Branches
MERGE INTO BRANCHES (BRANCH_CODE, BRANCH_NAME, PARTNER_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
KEY (BRANCH_CODE)
VALUES
-- SAMASTA branches
('AMEERPET', 'Ameerpet Branch', 'SAMASTA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KONDAPUR', 'Kondapur Branch', 'SAMASTA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- SONATA branches
('HITECH_CITY', 'Hitech City Branch', 'SONATA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BANJARA_HILLS', 'Banjara Hills Branch', 'SONATA', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- UJJIVAN branches
('SECUNDERABAD', 'Secunderabad Branch', 'UJJIVAN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JUBILEE_HILLS', 'Jubilee Hills Branch', 'UJJIVAN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BEGUMPET', 'Begumpet Branch', 'UJJIVAN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- BANDHAN branches
('LB_NAGAR', 'LB Nagar Branch', 'BANDHAN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DILSUKHNAGAR', 'Dilsukhnagar Branch', 'BANDHAN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- EQUITAS branches
('ATTAPUR', 'Attapur Branch', 'EQUITAS', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MEHDIPATNAM', 'Mehdipatnam Branch', 'EQUITAS', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- FINCARE branches
('UPPAL', 'Uppal Branch', 'FINCARE', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KOMPALLY', 'Kompally Branch', 'FINCARE', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
